name: Build and Create Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build for Windows
        run: dotnet publish -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -o ./publish/win-x64

      - name: Build for macOS (Apple Silicon)
        run: dotnet publish -c Release -r osx-arm64 --self-contained true -p:PublishSingleFile=true -o ./publish/osx-arm64

      - name: Create or Update GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            🚀 Automaticky vytvořený build
            - Commit: ${{ github.sha }}
            - Autor: ${{ github.actor }}
            - Windows (.exe)
            - macOS (ARM)
          artifacts: |
            publish/win-x64/*
            publish/osx-arm64/*
          allowUpdates: true
          replacesArtifacts: true
